### ISSUE TITLE
Performance of pretrained model 

### ISSUE THREAD

**Issue by vishal3477** [GewelsJI/DGNet#10]
Hi, 
The performance of the pretrained model is not the same as reported in the main paper. Can you please tell me the exact steps you used to generate the images and evaluation script used to get the performance? I used the python script to evaluate the maps generated by MyTest.py in pytorch folder. I'm getting the performace as shown below:
<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>

Dataset |   | Sm (↑) | wFm(↑) | MAE(↓)
-- | -- | -- | -- | --
CAMO | DGNet | 0.791 | 0.681 | 0.079
COD10K | DGNet | 0.776 | 0.603 | 0.046
NC4K | DGNet | 0.815 | 0.710 | 0.059

</body>

</html>

**Comment by GewelsJI** [comment]
we used the matlab-based toolbox to generate the reported metrics

**Comment by GewelsJI** [comment]
Hi, @vishal3477 
I would like to close this issue since I have not received any response from you. If you have any further questions, please feel free to reopen this page.
