### ISSUE TITLE
gradient data 

### ISSUE THREAD

**Issue by lgr1031** [GewelsJI/DGNet#11]
Where can find the gradient images for train model.

**Comment by GewelsJI** [comment]
All images are prepared at here: 
<img width="1098" alt="image" src="https://github.com/GewelsJI/DGNet/assets/38354957/b89d4d64-2b27-4cc3-b787-f52161bc2fee">

**Comment by lgr1031** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Daniel ***@***.***&gt;; 
发送时间: 2023年7月5日(星期三) 晚上9:07
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GewelsJI/DGNet] gradient data  (Issue #11)





 
All images are prepared at here:
