### ISSUE TITLE
The two pictures showing performance, parameters and MACs in the 1. Features section of your README

### ISSUE THREAD

**Issue by WkangLiu** [GewelsJI/DGNet#12]
Thank you for your excellent work. 

The two pictures showing performance, parameters and MACs in the 1. Features section of your README are very clear and beautiful. 

So much so that I am very interested in their production methods. 

Can you provide relevant  repositories or codes?

Looking forward to your reply!

**Comment by GewelsJI** [comment]
Sorry for late reply. We will update it in next few days. Please stay tuned for this page.

**Comment by GewelsJI** [comment]
Hello, guys,

Thank you for your patience.

The plotting code for Figure 7 in our paper is now available, which was written by @johnson111788 . We appreciate his recent efforts in cleaning up this code.

Please navigate to this repository: https://github.com/GewelsJI/DGNet/tree/main/lib_pytorch/utils/plotting

The code supports one-click generation; please feel free to use it!

Best regards,
Daniel.

**Comment by WkangLiu** [comment]
My goodness, thank you and @johnson111788 for your seriousness and effort on this, it is appreciated!
Being able to read the source code will definitely benefit me.
