### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [GewelsJI/DGNet#2]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.

- Zoo
  https://github.com/PINTO0309/PINTO_model_zoo

- ONNX, OpenVINO, TFJS, TensorFlow Lite, CoreML
  https://github.com/PINTO0309/PINTO_model_zoo/tree/main/299_DGNet

**Comment by GewelsJI** [comment]
Hi @PINTO0309 

Thank you first for your efforts. Here is the LICENSE: https://github.com/GewelsJI/DGNet/blob/main/LICENSE. You can feel free to use it under this restriction.

BTW, could we have a further talk via e-mail (gepengai.ji@gmail.com)?

Best regards,
Ge-Peng.

**Comment by PINTO0309** [comment]
Hi, @GewelsJI 
I am not a researcher, just a hobbyist playing around, but if that is ok with you I am fine with it. :+1: 

rmsdh122 [at] yahoo.co.jp
https://github.com/PINTO0309

Thank you for clarifying the license. I have cited it immediately.
