### ISSUE TITLE
Why is your model well generalized for different applications such as polyp/transparent segmentation?

### ISSUE THREAD

**Issue by muraano** [GewelsJI/DGNet#4]
First of all, thanks for your great work for camouflaged object detection(COD). I know segmentation task, but I am very new to COD.
I read your paper and am really surprised to your great result, but I have one question about polyp/transparent segmentation.
I understood a key feature of your model is to learn an object texture as well as an object shape. If this understanding is correct, I'm not sure why this  also improves the polyp/transparent segmentation accuracy because they don't seem to have a distinct texture.

**Comment by GewelsJI** [comment]
Hi, @muraano 

Thank you for putting forward such an excellent discussion here.

Yes. In our early experiments, we excitingly found that our model could perform well in some similar tasks, such as polyp/transparent/surface anomaly objects. Similar to COD, these task scenes contain camouflaged patterns in Figure 9.

Notably, the excellent generalization ability may be an open issue here. We provide a dual-branch framework comprising object texture and object semantic learners. The former could excavate the gradient-wise perspective's abundant texture cues of candidate object(s). The latter receives the texture cues and takes further aggregation via GIT. This could be viewed as the holistic semantic understanding of the current scene along with the texture (whether distinct or non-distinct).

Happy to receive your interesting idea or understanding.

Best.

**Comment by muraano** [comment]
Thanks for your answer!
