### ISSUE TITLE
有关object gradient

### ISSUE THREAD

**Issue by zhaolinGitHub** [GewelsJI/DGNet#5]
首先感谢你们很棒的工作。
我的疑问是：你们是不是没有在代码中提供有关canny检测器的代码？所以文中的object gradient需要我们自己来生成。如果是这样，有关canny检测器的参数设置是否可以告诉我们。
再次感谢

**Comment by GewelsJI** [comment]
你好，请参考：https://github.com/GewelsJI/DGNet/blob/main/dataset/Img2ObjGrad.py
